version: '3.8'

services:
  # 1. База данных
  movie_db:
    image: postgres:16
    container_name: movie_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: movie_recsys
    ports:
      - "5433:5432"  # Снаружи (в Windows) доступ по 5433, внутри 5432
    volumes:
      - movie_data:/var/lib/postgresql/data
    networks:
      - recsys_network
    # Умная проверка жизнеспособности базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d movie_recsys"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Бэкенд (FastAPI)
  backend:
    build: .
    container_name: movie_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY} # Явно указываем Docker'у взять этот ключ из .env
    depends_on:
      movie_db:
        condition: service_healthy # Бэкенд ждет, пока база не станет "здоровой"
    volumes:
      - .:/app  # Чтобы код обновлялся без пересборки (режим разработки)
    networks:
      - recsys_network

  # 3. MLflow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow_server
    ports:
      - "5000:5000"
    # Явно указываем пути внутри папки /app
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////app/mlflow.db --default-artifact-root /app/artifacts
    volumes:
      - ./mlflow_data:/app # Поменяли название папки на mlflow_data
    networks:
      - recsys_network

  # 4. Prometheus (Сборщик метрик)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - recsys_network

  # 5. Grafana (Дашборды)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - recsys_network
    depends_on:
      - prometheus

  # 6. Frontend (Streamlit UI)
  frontend:
    image: python:3.11-slim
    container_name: movie_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "pip install streamlit requests && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    networks:
      - recsys_network
    depends_on:
      - backend

networks:
  recsys_network:
    driver: bridge

volumes:
  movie_data:
  grafana_data: